spring.application.name=TestApplication
spring.datasource.url=jdbc:postgresql://localhost:5432/demo4?useSSL=false
#spring.datasource.url=jdbc:h2:file:/SpringBootDevelopment/TestApplication/db
spring.datasource.username=postgres
spring.datasource.password=Am@931063
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true








